import { MenuItem } from "./menu.model";
export const MENU: MenuItem[] = [
  // {
  //   id: 1,
  //   label: "MENUITEMS.DASHBOARDS.TEXT",
  //   Value: false,
  //   icon: "ri-dashboard-line",
  //   link: "/",
  // },
  {
    id: 2,
    label: "Organizational Dashboard",
    Value: false,
    icon: "ri-dashboard-fill",
    subItems: [
      {
        id: 5,
        label: "Approval Dashboard(Org)",
        link: "/organizational-dashboard/approval-dashboard",
        ScreenName: "organizationalApprovalDashboard",
        Value: false,
        parentId: 4,
      },

      {
        id: 5,
        label: "Accounts Dashboard(Org)",
        link: "/organizational-dashboard/accounts-dashboard",
        ScreenName: "AccountsDashboard",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Sales Dashboard(Org)",
        link: "/organizational-dashboard/sales-dashboard",
        ScreenName: "SalesDashboard",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Sales Analytics(Org)",
        link: "/organizational-dashboard/sales-analytics-dashboard",
        ScreenName: "salesAnalyticsDashboard",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Stock Dashboard(Org)",
        link: "/organizational-dashboard/stock-with-rates-dashboard",
        ScreenName: "StockWithRatesDashboard",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Profit/Loss Dashboard(Org)",
        link: "/organizational-dashboard/profit-loss-dashboard",
        ScreenName: "profitLossDashboard",
        Value: false,
        parentId: 4,
      },
    ],
  },
  {
    id: 2,
    label: "DashBoards",
    Value: false,
    icon: "ri-dashboard-line",
    subItems: [
      {
        id: 5,
        label: "Approval Dashboard",
        link: "/Approval-Dashboard",
        ScreenName: "PendingVouchersForApproval",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "new Approval Dashboard",
        link: "/Approval-Dashboard-new",
        ScreenName: "PendingVouchersForApproval",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Accounts Dashboard",
        link: "/accounts-dashboard",
        ScreenName: "AcFrmDashboard",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Accounts Dashboard",
        link: "/accounts-dashboard-trade-pro",
        ScreenName: "AccountsDashboardTradePro",
        Value: false,
        parentId: 4,
      },

      {
        id: 5,
        label: "Accounts Dashboard",
        link: "/accounts-dashboard-new",
        ScreenName: "AccountsDashboardNew",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Export Dashboard",
        link: "/export-dashboard",
        ScreenName: "ExportDashboard",
        Value: false,
        parentId: 4,
      },

      {
        id: 5,
        label: "Import Dashboard",
        link: "/import-dashboard",
        ScreenName: "ImportDashboard",
        Value: false,
        parentId: 4,
      },

      {
        id: 5,
        label: "Inventory Dashboard",
        link: "/inventory-dashboard-trade-pro",
        ScreenName: "ProfitLossDashboardTradePro",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Inventory Dashboard",
        link: "/inventory-dasboard",
        ScreenName: "InventoryDashboard",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Pending Work",
        link: "/Pending-Working",
        ScreenName: "InventoryPendingWorkDashboard",
        Value: false,
        parentId: 4,
      },
    ],
  },
  {
    id: 3,
    label: "Analytics Dashboard",
    Value: false,
    icon: "ri-line-chart-fill",
    subItems: [
      {
        id: 6,
        label: "Export Analytics",
        link: "/analytics/export-analytics",
        ScreenName: "frmExportAnalytics",
        Value: false,
        parentId: 4,
      },
      {
        id: 6,
        label: "Sales Analytics",
        link: "/analytics/sales-analytics",
        ScreenName: "frmSalesAnalytics",
        Value: false,
        parentId: 4,
      },
    ],
  },

  //==================================================================================================
  //Retail ERP Menu
  //#1:System Adim
  {
    id: 43,
    label: "System Admin",
    icon: "ri-settings-2-line",
    Value: false,
    subItems: [
      {
        id: 1,
        label: "System Configuration",
        link: "/admin-panel/system-configuration",
        ScreenName: "frmSystemConfiguration",
        Value: false,
        parentId: 43,
      },
      {
        id: 3,
        label: "Define Organization",
        link: "/admin-panel/define-organization",
        ScreenName: "frmDefineCompany",
        Value: false,
        parentId: 2,
      },
      {
        id: 3,
        label: "Define Company",
        link: "/admin-panel/define-company-history",
        ScreenName: "frmDefineCompany",
        Value: false,
        parentId: 2,
      },
      {
        id: 3,
        label: "Define User",
        link: "/admin-panel/define-user-history",
        ScreenName: "frmDefineUser",
        Value: false,
        parentId: 2,
      },
    ],
  },
  //#2:Accounts Management
  {
    id: 38,
    label: "Accounts Management",
    icon: "ri-pie-chart-line",
    Value: false,
    subItems: [
      {
        id: 3,
        label: "Chart of Account",
        link: "/accounts-definition/chart-of-account",
        ScreenName: "AcfrmDefCoa",
        Value: false,
        parentId: 2,
      },
      {
        id: 3,
        label: "Account Allocation",
        link: "/accounts-definition/accounts-allocation",
        ScreenName: "AcfrmAcAllocation",
        Value: false,
        parentId: 2,
      },
      {
        id: 3,
        label: "Accounts Opening Balance",
        link: "/accounts-definition/opening-balance",
        ScreenName: "AcfrmOpeningBalance",
        Value: false,
        parentId: 2,
      },
      {
        id: 31,
        label: "Payment Voucher",
        link: "/account-transaction/payment-voucher-history",
        ScreenName: "PaymentVoucherNew",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Fcy Payment Voucher",
        link: "/account-transaction/fcy-payment-voucher-history",
        ScreenName: "frmFcyPaymentVoucher",
        Value: false,
        parentId: 30,
      },
      {
        id: 37,
        label: "Receipt Voucher",
        link: "/account-transaction/receipt-voucher-history",
        ScreenName: "ReceiptsVoucherNew",
        Value: false,
        parentId: 30,
      },
      {
        id: 37,
        label: "Journal Voucher",
        link: "/account-transaction/voucher-entry-history",
        ScreenName: "VoucherEntry",
        Value: false,
        parentId: 30,
      },
      {
        id: 37,
        label: "Contra Voucher",
        link: "/account-transaction/contra-voucher-history",
        ScreenName: "ContraVoucher",
        Value: false,
        parentId: 30,
      },
    ],
  },
  {
    id: 2,
    label: "Admin Panel",
    Value: false,
    icon: "ri-settings-2-line",
    subItems: [
      {
        id: 3,
        label: "System Configuration",
        link: "/admin-panel/system-configuration",
        ScreenName: "frmSystemConfiguration",
        Value: false,
        parentId: 2,
      },
      {
        id: 3,
        label: "SMS Templates",
        link: "/admin-panel/sms-template",
        ScreenName: "frmSMSTemplate",
        Value: false,
        parentId: 2,
      },
      {
        id: 3,
        label: "Define Company",
        link: "/admin-panel/define-company-history",
        ScreenName: "frmDefineCompany",
        Value: false,
        parentId: 2,
      },
      {
        id: 3,
        label: "Define User",
        link: "/admin-panel/define-user-history",
        ScreenName: "frmDefineUser",
        Value: false,
        parentId: 2,
      },
    ],
  },

  {
    id: 2,
    label: "Account Definition",
    Value: false,
    icon: "ri-pie-chart-line",
    subItems: [
      {
        id: 3,
        label: "Chart of Account",
        link: "/accounts-definition/chart-of-account",
        ScreenName: "AcfrmDefCoa",
        Value: false,
        parentId: 2,
      },
      {
        id: 3,
        label: "Account Allocation",
        link: "/accounts-definition/accounts-allocation",
        ScreenName: "AcfrmAcAllocation",
        Value: false,
        parentId: 2,
      },
      {
        id: 3,
        label: "Accounts Opening Balance",
        link: "/accounts-definition/opening-balance",
        ScreenName: "AcfrmOpeningBalance",
        Value: false,
        parentId: 2,
      },
      {
        id: 31,
        label: "Account Budget",
        link: "/accounts-definition/accounts-budget-form",
        ScreenName: "AccountBudget",
        parentId: 30,
        Value: false,
      },
      {
        id: 3,
        label: "Define Bank",
        link: "/accounts-definition/bank",
        ScreenName: "AcfrmDefineBank",
        Value: false,
        parentId: 2,
      },
      {
        id: 3,
        label: "Cheque Book Registration",
        link: "/accounts-definition/cheque-book-registration-history",
        ScreenName: "frmChequeBookRegistration",
        Value: false,
        parentId: 2,
      },
      {
        id: 4,
        label: "Define Country",
        link: "/accounts-definition/country",
        ScreenName: "DefineCountry",
        Value: false,
        parentId: 2,
      },
    ],
  },
  {
    id: 30,
    label: "Accounts Transaction",
    icon: " ri-funds-line",
    Value: false,
    subItems: [
      {
        id: 31,
        label: "Fcy Bank Receipt",
        link: "/account-transaction/fc-bank-receipt-history",
        ScreenName: "Acfrmfcbankreceipt",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Export Invoice Voucher",
        link: "/account-transaction/export-invoice-voucher-history",
        ScreenName: "frmExportInvoiceVoucher",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Payment Voucher",
        link: "/account-transaction/payment-voucher-history",
        ScreenName: "PaymentVoucherNew",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Fcy Payment Voucher",
        link: "/account-transaction/fcy-payment-voucher-history",
        ScreenName: "frmFcyPaymentVoucher",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Payment By Invoice",
        link: "/account-transaction/payment-by-invoice-voucher-history",
        ScreenName: "PaymentByInvoiceAccount",
        Value: false,
        parentId: 30,
      },
      {
        id: 37,
        label: "Receipt Voucher",
        link: "/account-transaction/receipt-voucher-history",
        ScreenName: "ReceiptsVoucherNew",
        Value: false,
        parentId: 30,
      },
      {
        id: 37,
        label: "Contra Voucher",
        link: "/account-transaction/contra-voucher-history",
        ScreenName: "ContraVoucher",
        Value: false,
        parentId: 30,
      },
      {
        id: 37,
        label: "Journal Voucher",
        link: "/account-transaction/voucher-entry-history",
        ScreenName: "VoucherEntry",
        Value: false,
        parentId: 30,
      },
      {
        id: 37,
        label: "Bills of Payables",
        link: "/account-transaction/bills-of-payable-history",
        ScreenName: "frmBillsPayables",
        Value: false,
        parentId: 30,
      },
      {
        id: 37,
        label: "Bills of Receivables",
        link: "/account-transaction/bills-receivable-history",
        ScreenName: "frmBillsReceivables",
        Value: false,
        parentId: 30,
      },
      {
        id: 37,
        label: "Expense Voucher",
        link: "/account-transaction/expense-voucher-history",
        ScreenName: "ExpenseVoucher",
        Value: false,
        parentId: 30,
      },
    ],
  },
  //#3:Accounts Reports
  {
    id: 4,
    label: "Account Reports",
    icon: "ri-file-chart-line",
    Value: false,
    subItems: [
      // {
      //   id: 5,
      //   label: "Approval Dashboard",
      //   link: "/account-reports/Approval Dashboard",
      //   ScreenName: "AcfrmApprovalDashboard",
      //   Value: false,
      //   parentId: 4,
      // },
      // {
      //   id: 5,
      //   label: "Account Dashboard",
      //   link: "/account-reports/accounts-dashboard",
      //   ScreenName: "AcFrmDashboard",
      //   Value: false,
      //   parentId: 4,
      // },
      {
        id: 5,
        label: "Chart of Account",
        link: "/account-reports/coa",
        ScreenName: "ChartOfAccount",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Fcy Bank Receipt",
        link: "/account-reports/fcy-bank-receipt",
        ScreenName: "FcyBankReceipt",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Fcy Payable/Recievable",
        link: "/account-reports/fcy-payables-receivables-rpt",
        ScreenName: "FCYPayablesAndReceivablesRpt",
        Value: false,
        parentId: 4,
      },
      {
        id: 6,
        label: "Voucher Reports",
        link: "/account-reports/voucher-reports",
        ScreenName: "VoucherReport",
        Value: false,
        parentId: 4,
      },
      {
        id: 7,
        label: "Voucher Validation",
        link: "/account-reports/voucher-validation",
        ScreenName: "VoucherValidation",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Unbalanced Voucher",
        link: "/account-reports/unbalanced-voucher-dashboard",
        ScreenName: "AuditDashboard",
        Value: false,
        parentId: 4,
      },
      {
        id: 8,
        label: "Activity Summary",
        link: "/account-reports/activity-summary",
        ScreenName: "ActicitySummery",
        Value: false,
        parentId: 4,
      },
      {
        id: 12,
        label: "Bank Book",
        link: "/account-reports/bank-balances",
        ScreenName: "BankBalances",
        Value: false,
        parentId: 4,
      },
      {
        id: 12,
        label: "Cash Book",
        link: "/account-reports/cash-balances",
        ScreenName: "CashBalances",
        Value: false,
        parentId: 4,
      },
      {
        id: 9,
        label: "General Ledger",
        link: "/account-reports/general-ledger",
        ScreenName: "GeneralLedger",
        Value: false,
        parentId: 4,
      },
      {
        id: 9,
        label: "Fcy General Ledger",
        link: "/account-reports/fcy-general-ledger",
        ScreenName: "FcyGeneralLedgerRpt",
        Value: false,
        parentId: 4,
      },
      {
        id: 10,
        label: "Account Statement",
        link: "/account-reports/account-statement",
        ScreenName: "GeneralLedgerStatment",
        Value: false,
        parentId: 4,
      },
      {
        id: 13,
        label: "Payables New",
        link: "/account-reports/payables-report-new",
        ScreenName: "Payables",
        Value: false,
        parentId: 4,
      },
      {
        id: 13,
        label: "Payable",
        link: "/account-reports/payable",
        ScreenName: "Payables",
        Value: false,
        parentId: 4,
      },
      {
        id: 13,
        label: "Payable Aging",
        link: "/account-reports/payable-aging",
        ScreenName: "PayablesAging",
        Value: false,
        parentId: 4,
      },
      {
        id: 13,
        label: "Receivable (New)",
        link: "/account-reports/receivables-report-new",
        ScreenName: "Receivables",
        Value: false,
        parentId: 4,
      },
      {
        id: 13,
        label: "Receivable",
        link: "/account-reports/receivable",
        ScreenName: "Receivables",
        Value: false,
        parentId: 4,
      },

      {
        id: 13,
        label: "Receivable Aging",
        link: "/account-reports/receivable-aging",
        ScreenName: "ReceivableAging",
        Value: false,
        parentId: 4,
      },
      {
        id: 5,
        label: "Payables Recievables Aging",
        link: "/account-reports/payables-recievables-aging",
        ScreenName: "FCYPayablesAndReceivablesAgingRpt",
        Value: false,
        parentId: 4,
      },
      {
        id: 13,
        label: "Receivable FollowUp",
        link: "/account-reports/receivableFollowUp-history",
        ScreenName: "ReceivablesFollowUps",
        Value: false,
        parentId: 4,
      },
      {
        id: 11,
        label: "Trial Balance",
        link: "/account-reports/trial-balance",
        ScreenName: "TrialBalance",
        Value: false,
        parentId: 4,
      },
      {
        id: 12,
        label: "Selected Trial Balance",
        link: "/account-reports/trial-balance-selected",
        ScreenName: "SelectedTrialBalance",
        Value: false,
        parentId: 4,
      },
      {
        id: 12,
        label: "Trial Balance All",
        link: "/account-reports/trial-balance-all-level",
        ScreenName: "SelectedTrialBalanceAllLevel",
        Value: false,
        parentId: 4,
      },
      {
        id: 10,
        label: "Balance Sheet",
        link: "/account-reports/balance-sheet",
        ScreenName: "AccountsBalanceSheetStandardRpt",
        Value: false,
        parentId: 4,
      },
      {
        id: 12,
        label: "Job Managment",
        link: "/account-reports/job-managment-ledger",
        ScreenName: "JobManagmentReport",
        Value: false,
        parentId: 4,
      },
    ],
  },
  //#4:Inventory Defination

  //#5:Import/Purchases

  //#6:Sales/Pos

  //#7:

  {
    id: 30,
    label: "Customer Sales",
    icon: "ri-shopping-cart-2-line",
    Value: false,
    subItems: [
      {
        id: 31,
        label: "bank-Receipt-design",
        link: "/cus-sales/FCY-bank-Receipt-design",
        ScreenName: "SaleOrder",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Keys New Design",
        link: "/cus-sales/Keys-new-design",
        ScreenName: "SaleOrder",
        Value: true,
        parentId: 30,
      },
      {
        id: 31,
        label: "gatepass-inward",
        link: "/cus-sales/gatepass-inward-history",
        ScreenName: "SaleOrder",
        Value: true,
        parentId: 30,
      },
      {
        id: 31,
        label: "FCY Payment",
        link: "/cus-sales/fcy-payment-voucher-history",
        ScreenName: "SaleOrder",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Bank Receipt",
        link: "/cus-sales/fc-bank-receipt-history",
        ScreenName: "SaleOrder",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Sale Order",
        link: "/cus-sales/sale-order-history",
        ScreenName: "SaleOrder",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Purchase Order extra",
        link: "/cus-sales/purchase-order-history",
        ScreenName: "SaleOrder",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Purchase Invoice extra",
        link: "/cus-sales/purchase-invoice-history",
        ScreenName: "SaleOrder",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Pre Production Lab",
        link: "/cus-sales/pre-production-history",
        ScreenName: "SaleOrder",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Delivery  Order",
        link: "/cus-sales/delivery-order-history",
        ScreenName: "DeliveryOrder",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Gatepass Outward",
        link: "/cus-sales/gatepass-outward-history",
        ScreenName: "OutwardGatePass",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Goods Dispatch Notes",
        link: "/cus-sales/goods-dispatch-notes-history",
        ScreenName: "InvfrmGDN",
        Value: false,
        parentId: 30,
      },
      {
        id: 32,
        label: "Sales Invoice",
        link: "/cus-sales/sale-invoice-history",
        ScreenName: "InvfrmSaleInvoice",
        Value: false,
        parentId: 30,
      },
    ],
  },

  //#8:Retail Inventory Reports

  {
    id: 20,
    label: "Inventory Reports",
    Value: false,
    icon: "ri-stock-line",
    subItems: [
      {
        id: 21,
        label: "Purchse Order Register",
        link: "/inventory-reports/purchase-order-register",
        ScreenName: "PurchaseOrderHistory",
        Value: false,
        parentId: 20,
      },
      {
        id: 21,
        label: "Purchase Order Register",
        link: "/inventory-reports/purchase-order-trading-register",
        ScreenName: "PurchaseOrderTradingRegister",
        Value: false,
        parentId: 20,
      },
      {
        id: 21,
        label: "GP Inward Register",
        link: "/inventory-reports/gatepass-Inward-history",
        ScreenName: "frmGatePassReport",
        Value: false,
        parentId: 20,
      },
      {
        id: 23,
        label: "Goods Receipt Register",
        link: "/inventory-reports/grn-history",
        ScreenName: "frmGRNHistory",
        Value: false,
        parentId: 20,
      },
      {
        id: 26,
        label: "Purchase Register",
        link: "/inventory-reports/purchase-invoice-register",
        ScreenName: "frmPurchaseInvoiceHistory",
        Value: false,
        parentId: 20,
      },
      {
        id: 22,
        label: "Sale Order Register",
        link: "/inventory-reports/sale-order-history",
        ScreenName: "frmSaleOrderHistory",
        Value: false,
        parentId: 20,
      },
      // {
      //   id: 21,
      //   label: "SaleBill Trade",
      //   link: "/inventory-reports/sale-invoice-trade-pro-slip",
      //   ScreenName: "frmSaleInvoiceDirectRegister",
      //   Value: false,
      //   parentId: 20,
      // },
      {
        id: 22,
        label: "Delivery Order Register",
        link: "/inventory-reports/delivery-order-history",
        ScreenName: "frmDeliveryOrderForApprovel",
        Value: false,
        parentId: 20,
      },
      {
        id: 22,
        label: "GP Outward Register",
        link: "/inventory-reports/gatepass-outward-history",
        ScreenName: "frmGPOutward",
        Value: false,
        parentId: 20,
      },
      {
        id: 24,
        label: "Goods Despatch Register",
        link: "/inventory-reports/gdn-history",
        ScreenName: "frmGDNHistory",
        Value: false,
        parentId: 20,
      },
      {
        id: 21,
        label: "Sale Register",
        link: "/inventory-reports/sale-invoice-history",
        ScreenName: "frmSaleInvoiceHistory",
        Value: false,
        parentId: 20,
      },
      {
        id: 21,
        label: "Purchase Invoice Register",
        link: "/inventory-reports/purchase-invoice-trading",
        ScreenName: "PurchaseInvoiceTrading",
        Value: false,
        parentId: 20,
      },
      {
        id: 21,
        label: "Sale Invoice Register",
        link: "/inventory-reports/sale-invoice-trading",
        ScreenName: "SaleInvoiceTrading",
        Value: false,
        parentId: 20,
      },
      // {
      //   id: 21,
      //   label: "Sale Direct Register",
      //   link: "/inventory-reports/sale-invoice-direct-register",
      //   ScreenName: "frmSaleInvoiceDirectRegister",
      //   Value: false,
      //   parentId: 20,
      // },
      {
        id: 24,
        label: "Weigh Bridge Register",
        link: "/inventory-reports/weighbridge-history",
        ScreenName: "frmWeightBridgeHistory",
        Value: false,
        parentId: 20,
      },
      // {
      //   id: 25,
      //   label: "Item Ledger",
      //   link: "/inventory-reports/item-ledger",
      //   ScreenName: "ItemLedger",
      //   Value: false,
      //   parentId: 20,
      // },
      {
        id: 25,
        label: "Item List",
        link: "/inventory-reports/item-List",
        ScreenName: "frmRptItemList",
        Value: false,
        parentId: 20,
      },
    ],
  },

  {
    id: 30,
    label: "Lab",
    icon: " ri-flask-line",
    Value: false,
    subItems: [
      {
        id: 31,
        label: "Define Perameters",
        link: "/lab/lab-item-perameter",
        ScreenName: "InvLabAnalysisItems",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Define Group",
        link: "/lab/lab-item-group",
        ScreenName: "InvLabAnalysisGroup",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Analysis Group Standard",
        link: "/lab/anlysis-group-standard",
        ScreenName: "InvLabGroupAnalysisStandards",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Sample Log Register",
        link: "/lab/sample-log-register",
        ScreenName: "InvLabSampleLogRegister",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Sample Analysis",
        link: "/lab/sample-analysis-history",
        ScreenName: "InvLabSampleAnalysis",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Purchase Analysis",
        link: "/lab/purchase-analysis-history",
        ScreenName: "InvLabPurchaseAnalysis",
        Value: false,
        parentId: 30,
      },
      {
        id: 31,
        label: "Pre Shipment Analysis",
        link: "/inventory-definition/PreProduction-Lab-Inspection-history",
        ScreenName: "EximPreProductionLab",
        Value: false,
        parentId: 30,
      },
    ],
  },

  {
    id: 50,
    label: "Production",
    Value: false,
    icon: "ri-bank-line",
    subItems: [
      {
        id: 52,
        label: "inv Food Production",
        link: "/production/inv-food-production/inv-food-porduction",
        ScreenName: "frmInvStockConversionTrade",
        Value: false,
        parentId: 50,
      },
      {
        id: 52,
        label: "Variety Conversion Trade",
        link: "/production/variety-conversion-trade-pro-history",
        ScreenName: "frmInvStockConversionTrade",
        Value: false,
        parentId: 50,
      },
      {
        id: 51,
        label: "Production Job Order",
        link: "/production/production-job-order-history",
        ScreenName: "frmProductionJobOrder",
        Value: false,
        parentId: 50,
      },
      {
        id: 52,
        label: "Variety Conversion",
        link: "/production/variety-conversion-history",
        ScreenName: "invfrmStockConversionProduction",
        Value: false,
        parentId: 50,
      },
      {
        id: 54,
        label: "Food Production",
        link: "/production/food-production-history",
        ScreenName: "frmFoodProduction",
        parentId: 50,
        Value: false,
      },
    ],
  },
  {
    id: 50,
    label: "Stock Reports",
    icon: "ri-slideshow-line",
    Value: false,
    subItems: [
      {
        id: 51,
        label: "Item Ledger",
        link: "/stock-reports/stock-evaluation",
        ScreenName: "RptGenrateStocks",
        Value: false,
        parentId: 50,
      },
      {
        id: 51,
        label: "Stock Transaction",
        link: "/stock-reports/rice-stock-transaction",
        ScreenName: "InventoryTransactionReport",
        Value: false,
        parentId: 50,
      },
      {
        id: 51,
        label: "Stock Report",
        link: "/stock-reports/stock-report",
        ScreenName: "frmStockReport",
        Value: false,
        parentId: 50,
      },
      {
        id: 51,
        label: "Stock Report (Avg Rates)",
        link: "/stock-reports/stock-report-with-average-rates",
        ScreenName: "StockReportWithAvgRates",
        Value: false,
        parentId: 50,
      },
      {
        id: 51,
        label: "Stock Report TradePro",
        link: "/stock-reports/stock-report-tradepro",
        ScreenName: "frmStockReportTradePro",
        Value: false,
        parentId: 50,
      },
      {
        id: 51,
        label: "Item Ledger TradePro",
        link: "/stock-reports/item-ledger-report-tradePro",
        ScreenName: "GeneralLedgerFromAc",
        Value: false,
        parentId: 50,
      },
    ],
  },

  // {
  //   id: 50,
  //   label: "Weigh Bridge",
  //   icon: "ri-bank-line",
  //   Value: false,
  //   subItems: [
  //     {
  //       id: 51,
  //       label: "Weigh Bridge",
  //       link: "/weigh-bridge/weigh-bridge-history",
  //       Value: false,
  //       parentId: 50,
  //     },
  //   ],
  // },
];
